Misc: Fix unacceptable character #x1f437 (#748)
In the file `envs/prod/17app/stream/providers.yaml`
We have OpenID in comment lines, but OpenID will contains emoji, which will be reject by PyYAML loader (see the error message below), so switching to `ruamel.yaml` to load emoji characters without checking `NON_PRINTABLE` characters [1].

1: https://github.com/yaml/pyyaml/blob/5.1.1/lib3/yaml/reader.py#L137-L144

```
Traceback (most recent call last):
  File "./tools/check_duplicate_users.py", line 13, in <module>
    data = yaml.safe_load(f)
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.7/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/usr/local/lib/python3.7/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/usr/local/lib/python3.7/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x1f437: special characters are not allowed
  in "envs/prod/17app/stream/providers.yaml", position 1847
```